// <auto-generated />
using System;
using FlowLine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowLine.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(FlowLineDbContext))]
    [Migration("20260702154906_RenameStaffTable")]
    partial class RenameStaffTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowLine.Domain.Entities.External.HistoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeNumber")
                        .HasColumnType("int")
                        .HasColumnName("Assigne Number");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Channel");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<bool>("IsTested")
                        .HasColumnType("bit")
                        .HasColumnName("IsTested");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderId");

                    b.Property<string>("PackedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PackedBy");

                    b.Property<DateTime?>("PackedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PackedDate");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("QTY");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SKU");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("TestedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TestedBy");

                    b.HasKey("Id");

                    b.ToTable("History", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.External.StaffMember", b =>
                {
                    b.Property<int>("StaffNumber")
                        .HasColumnType("int")
                        .HasColumnName("StaffNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int?>("TestingPower")
                        .HasColumnType("int")
                        .HasColumnName("TestingPower");

                    b.HasKey("StaffNumber");

                    b.ToTable("StaffTable", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.StepCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("StepId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("StepCompletions");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClaimedByStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStageId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByStationId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("CurrentStageId", "Status", "ClaimedByStationId", "QueuedAtUtc");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresPrebuild")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkflowAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StaffNumber")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "StaffNumber")
                        .IsUnique();

                    b.ToTable("WorkflowAssignments");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Step", "Step")
                        .WithMany("MediaAssets")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Stage", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Station", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Stage", "Stage")
                        .WithMany("Stations")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Step", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Stage", "Stage")
                        .WithMany("Steps")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.StepCompletion", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Station", "Station")
                        .WithMany("Completions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowLine.Domain.Entities.Step", "Step")
                        .WithMany("Completions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLine.Domain.Entities.WorkItem", "WorkItem")
                        .WithMany("StepCompletions")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Step");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkItem", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Station", "ClaimedByStation")
                        .WithMany("ClaimedWorkItems")
                        .HasForeignKey("ClaimedByStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlowLine.Domain.Entities.Stage", "CurrentStage")
                        .WithMany("CurrentWorkItems")
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLine.Domain.Entities.Workflow", "Workflow")
                        .WithMany("WorkItems")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimedByStation");

                    b.Navigation("CurrentStage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkflowAssignment", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Stage", b =>
                {
                    b.Navigation("CurrentWorkItems");

                    b.Navigation("Stations");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Station", b =>
                {
                    b.Navigation("ClaimedWorkItems");

                    b.Navigation("Completions");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Step", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkItem", b =>
                {
                    b.Navigation("StepCompletions");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Stages");

                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
