// <auto-generated />
using System;
using FlowLine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowLine.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FlowLineDbContext))]
    [Migration("20260703132050_AddWorkflowAllowAdHocStart")]
    partial class AddWorkflowAllowAdHocStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("FlowLine.Domain.Entities.External.HistoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("AssigneeNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedNumber");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT")
                        .HasColumnName("Channel");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<bool>("IsTested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsTested");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Orderid");

                    b.Property<string>("PackedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("PackedBy");

                    b.Property<DateTime?>("PackedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("PackedDate");

                    b.Property<string>("Qty")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("QTY");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SKU");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("TestStatus");

                    b.Property<string>("TestedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("TestedBy");

                    b.HasKey("Id");

                    b.ToTable("History", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.External.StaffMember", b =>
                {
                    b.Property<int>("StaffNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StaffNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int?>("TestingPower")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TestingPower");

                    b.HasKey("StaffNumber");

                    b.ToTable("StaffTable", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresScan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.StepCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedByStaffNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("StepId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("StepCompletions");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaimedByStationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByStationId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("CurrentStageId", "Status", "ClaimedByStationId", "QueuedAtUtc");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAdHocStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresPrebuild")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkflowAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "StaffNumber")
                        .IsUnique();

                    b.ToTable("WorkflowAssignments");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Step", "Step")
                        .WithMany("MediaAssets")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Stage", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Station", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Stage", "Stage")
                        .WithMany("Stations")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Step", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Stage", "Stage")
                        .WithMany("Steps")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.StepCompletion", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Station", "Station")
                        .WithMany("Completions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowLine.Domain.Entities.Step", "Step")
                        .WithMany("Completions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLine.Domain.Entities.WorkItem", "WorkItem")
                        .WithMany("StepCompletions")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Step");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkItem", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Station", "ClaimedByStation")
                        .WithMany("ClaimedWorkItems")
                        .HasForeignKey("ClaimedByStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlowLine.Domain.Entities.Stage", "CurrentStage")
                        .WithMany("CurrentWorkItems")
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLine.Domain.Entities.Workflow", "Workflow")
                        .WithMany("WorkItems")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimedByStation");

                    b.Navigation("CurrentStage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkflowAssignment", b =>
                {
                    b.HasOne("FlowLine.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Stage", b =>
                {
                    b.Navigation("CurrentWorkItems");

                    b.Navigation("Stations");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Station", b =>
                {
                    b.Navigation("ClaimedWorkItems");

                    b.Navigation("Completions");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Step", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.WorkItem", b =>
                {
                    b.Navigation("StepCompletions");
                });

            modelBuilder.Entity("FlowLine.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Stages");

                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
